apiVersion: apps/v1
kind: Deployment
metadata:
 name: app
spec:
 selector:
  matchLabels:
   app: app
 replicas: 3
 template:
  metadata:
   labels:
    app: app
  spec:
   containers:
    - name: app
      image: sin.ocir.io/axf5p8j94qn5/oke-clus-1-cr:v1
      imagePullPolicy: Always
      ports:
      - name: app
        containerPort: 4000
        protocol: TCP
   imagePullSecrets:
   - name: ocisecret 
---
apiVersion: v1
kind: Service
metadata:
 name: app-lb
 labels:
  app: app
 annotations:
  service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
  service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
  service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 4000
  selector:
    app: app
